/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.utiles.ControladorPersona;
import Controlador.utiles.TipoOrdenacion;
import Modelo.ListaEnlazadaServices;
import Modelo.Persona;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Vista extends javax.swing.JFrame {

    int pos = -1;
    boolean editaP = false;
    ControladorPersona cc = new ControladorPersona();

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            cc.cargar();
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("No se han podido cargar Personas");
        }
        cargarTabla(cc.getListaPersona());

    }

    public void limpiar() {

        pos = -1;
        editaP = false;
    }

    public void cargarTabla(ListaEnlazadaServices<Persona> lec) {
        TablaPersonas tc = new TablaPersonas(lec);
        tbl_Ta.setModel(tc);
        tbl_Ta.updateUI();
    }

    public void ordenar() throws Exception {
        String atributo = cbxAtri.getSelectedItem().toString();
        TipoOrdenacion tipoOrdenacion = TipoOrdenacion.valueOf(cbxTip.getSelectedItem().toString());
        switch (cbxMet.getSelectedIndex()) {
            case 0:
                System.out.println("QuickSort : " + atributo + ", " + tipoOrdenacion.toString());
                cc.getListaPersona().setLista(cc.getListaPersona().getLista().quicksort(atributo, tipoOrdenacion, 0, cc.getListaPersona().getLista().getSize() - 1));
                System.out.println("Ordenanda");
                break;
            case 1:
                System.out.println("Shell : " + atributo + ", " + tipoOrdenacion.toString());
                cc.getListaPersona().setLista(cc.getListaPersona().getLista().ordenar_Shell(atributo, tipoOrdenacion));
                System.out.println("Ordenada");
                break;
        }
        cargarTabla(cc.getListaPersona());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ta = new javax.swing.JTable();
        cbxAtri = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxMet = new javax.swing.JComboBox<>();
        cbxTip = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Personas"));
        jPanel2.setLayout(null);

        tbl_Ta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Ta);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 440, 260);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 470, 290);

        cbxAtri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "cedula", "numcelular" }));
        jPanel1.add(cbxAtri);
        cbxAtri.setBounds(560, 80, 90, 30);

        jLabel1.setText("Ordenar:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 30, 60, 20);

        cbxMet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QuickSort()", "Shell()" }));
        cbxMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMetActionPerformed(evt);
            }
        });
        jPanel1.add(cbxMet);
        cbxMet.setBounds(560, 130, 90, 20);

        cbxTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCENDENTE", "DESCENDENTE" }));
        jPanel1.add(cbxTip);
        cbxTip.setBounds(560, 180, 90, 20);

        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 240, 73, 23);

        jLabel2.setText("Atributo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 90, 50, 14);

        jLabel3.setText("Método:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 140, 50, 14);

        jLabel4.setText("Tipo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(494, 180, 40, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            ordenar();        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAtri;
    private javax.swing.JComboBox<String> cbxMet;
    private javax.swing.JComboBox<String> cbxTip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Ta;
    // End of variables declaration//GEN-END:variables
}
